## Exploratory Data Analysis

In [20]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [21]:
employee_df = pd.read_excel('Indian_HR_Dataset.xlsx')

In [22]:
employee_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 17 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Employee_ID                  100000 non-null  int64
 1   Name                         100000 non-null  object
 2   Department                   100000 non-null  object
 3   Gender                       100000 non-null  object
 4   Age                          100000 non-null  int64
 5   Job_Title                    100000 non-null  object
 6   Hire_Date                    100000 non-null  object
 7   Years_At_Company             100000 non-null  int64
 8   Education_Level              100000 non-null  object
 9   Performance_Score            100000 non-null  int64
 10  Monthly_Salary               100000 non-null  int64
 11  Work_Hours_Per_Week          100000 non-null  int64
 12  Projects_Handled             100000 non-null  int64
 13  Remote_Work_Frequency        100000 non-null  int64
 14  Promotions                   100000 non-null  int64
 15  Employee_Satisfaction_Score  100000 non-null  float64
 16  Resigned                     100000 non-null  bool
dtypes: bool(1), float64(1), int64(9), object(6)
memory usage: 12.3+ MB

In [23]:
employee_df.isnull().sum()/employee_df.shape[0]

Employee_ID                    0.0
Name                           0.0
Department                     0.0
Gender                         0.0
Age                            0.0
Job_Title                      0.0
Hire_Date                      0.0
Years_At_Company               0.0
Education_Level                0.0
Performance_Score              0.0
Monthly_Salary                 0.0
Work_Hours_Per_Week            0.0
Projects_Handled               0.0
Remote_Work_Frequency          0.0
Promotions                     0.0
Employee_Satisfaction_Score    0.0
Resigned                       0.0
dtype: float64

In [24]:
employee_df.shape

(100000, 17)

In [25]:
employee_df.describe(include = 'all')

,Employee_ID,Name,Department,Gender,Age,Job_Title,Hire_Date,Years_At_Company,Education_Level,Performance_Score,Monthly_Salary,Work_Hours_Per_Week,Projects_Handled,Remote_Work_Frequency,Promotions,Employee_Satisfaction_Score,Resigned
count,100000.000000,100000,100000,100000,100000.000000,100000,100000,100000.000000,100000,100000.000000,1.000000e+05,100000.00000,100000.000000,100000.000000,100000.00000,100000.000000,100000
unique,NaN,40039,9,2,NaN,9,8650,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
top,NaN,Anand Kadam,Engineering,Male,NaN,Analyst,2023-10-18,NaN,Bachelor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
freq,NaN,4,20009,55000,NaN,19876,52,NaN,56425,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71783
mean,50000.500000,NaN,NaN,NaN,38.502540,NaN,NaN,5.834810,NaN,3.195550,1.400593e+05,45.17006,24.028400,26.607200,1.13271,3.484508,NaN
std,28867.657797,NaN,NaN,NaN,12.119688,NaN,NaN,5.157211,NaN,0.843159,1.430374e+05,3.65081,20.756368,30.596638,1.44459,0.862410,NaN
min,1.000000,NaN,NaN,NaN,18.000000,NaN,NaN,0.000000,NaN,1.000000,1.800000e+04,40.00000,1.000000,0.000000,0.00000,1.000000,NaN
25%,25000.750000,NaN,NaN,NaN,28.000000,NaN,NaN,2.000000,NaN,3.000000,6.500000e+04,42.00000,9.000000,0.000000,0.00000,2.890000,NaN
50%,50000.500000,NaN,NaN,NaN,38.000000,NaN,NaN,4.000000,NaN,3.000000,9.600000e+04,45.00000,18.000000,20.000000,1.00000,3.510000,NaN
75%,75000.250000,NaN,NaN,NaN,49.000000,NaN,NaN,8.000000,NaN,4.000000,1.620000e+05,48.00000,33.000000,50.000000,2.00000,4.110000,NaN
max,100000.000000,NaN,NaN,NaN,59.000000,NaN,NaN,35.000000,NaN,5.000000,2.518000e+06,60.00000,196.000000,100.000000,6.00000,5.000000,NaN

In [26]:
employee_df.nunique()

Employee_ID                    100000
Name                            40039
Department                          9
Gender                              2
Age                                42
Job_Title                           9
Hire_Date                        8650
Years_At_Company                   36
Education_Level                     4
Performance_Score                   5
Monthly_Salary                   1211
Work_Hours_Per_Week                21
Projects_Handled                  160
Remote_Work_Frequency               5
Promotions                          7
Employee_Satisfaction_Score       401
Resigned                            2
dtype: int64

In [27]:
employee_df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Length: 100000, dtype: bool

In [28]:
def identify_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3-Q1

    lower_bound = Q1-1.5*IQR
    upper_bound = Q3+1.5*IQR

    return df[(df[column] < lower_bound) | (df[column] > upper_bound)]

In [29]:
imp_cols = employee_df.select_dtypes(include = [np.number]).columns
imp_cols = imp_cols.drop(['Employee_ID','Remote_Work_Frequency'])
imp_cols

Index(['Age', 'Years_At_Company', 'Performance_Score', 'Monthly_Salary',
       'Work_Hours_Per_Week', 'Projects_Handled', 'Promotions',
       'Employee_Satisfaction_Score'],
      dtype='object')

In [30]:
for col in imp_cols:
    outliers = identify_outliers(employee_df,col)
    print(outliers)

Empty DataFrame
Columns: [Employee_ID, Name, Department, Gender, Age, Job_Title, Hire_Date, Years_At_Company, Education_Level, Performance_Score, Monthly_Salary, Work_Hours_Per_Week, Projects_Handled, Remote_Work_Frequency, Promotions, Employee_Satisfaction_Score, Resigned]
Index: []
       Employee_ID                 Name        Department  Gender  Age  \
48              49          Padma Dixit  Customer Support  Female   56
115            116      Shashank Mallya        Operations    Male   49
142            143       Akash Rajkhowa                IT    Male   56
161            162        Kabir Mahajan             Sales    Male   54
198            199       Jeevan Goswami             Sales    Male   50
...            ...                  ...               ...     ...  ...
99874        99875         Mansi Haldar        Operations  Female   58
99893        99894  Gaurav Bhattacharya       Engineering    Male   51
99895        99896      Suraj Bhatnagar                IT    Male   55
99910        99911        Santosh Reddy             Legal    Male   47
99956        99957    Nishtha Deshpande  Customer Support  Female   52

         Job_Title   Hire_Date  Years_At_Company Education_Level  \
48     Sr. Manager  2001-07-22                23        Bachelor
115      Developer  2006-12-04                18          Master
142        Manager  1997-10-03                27        Bachelor
161        Analyst  2006-02-12                19        Bachelor
198      Developer  2005-09-03                19          Master
...            ...         ...               ...             ...
99874    Developer  1997-08-24                27        Bachelor
99893   Technician  2006-08-06                18     High School
99895  Sr. Manager  2002-09-23                22             PhD
99910     Engineer  2006-10-30                18        Bachelor
99956   Technician  2001-01-14                24     High School

       Performance_Score  Monthly_Salary  Work_Hours_Per_Week  \
48                     3          738000                   41
115                    4          290000                   48
142                    3          562000                   45
161                    4          125000                   43
198                    3          274000                   46
...                  ...             ...                  ...
99874                  5          281000                   41
99893                  4           75000                   42
99895                  4          849000                   42
99910                  4          158000                   46
99956                  4           84000                   41

       Projects_Handled  Remote_Work_Frequency  Promotions  \
48                   27                     50           5
115                  75                     50           6
142                  56                     50           6
161                  87                     20           3
198                  87                     50           4
...                 ...                    ...         ...
99874                95                     50           5
99893               113                      0           6
99895                20                     20           3
99910                70                     20           3
99956               118                      0           6

       Employee_Satisfaction_Score  Resigned
48                            2.98     False
115                           4.42     False
142                           4.17     False
161                           3.22      True
198                           4.07     False
...                            ...       ...
99874                         3.17     False
99893                         3.87     False
99895                         4.02     False
99910                         2.89     False
99956                         3.83     False

[3684 rows x 17 columns]
       Employee_ID              Name   Department  Gender  Age   Job_Title  \
93              94      Palak Shukla   Operations  Female   38     Manager
130            131       Parul Yadav           IT  Female   51     Analyst
156            157    Namita Acharya  Engineering  Female   38    Engineer
195            196    Archana Mishra           IT  Female   37     Analyst
196            197      Anurag Dutta           IT    Male   34  Technician
...            ...               ...          ...     ...  ...         ...
99430        99431        Tejas Mane           IT    Male   48   Developer
99581        99582       Ekta Mishra      Finance  Female   36     Manager
99637        99638        Sneha Bose  Engineering  Female   32   Developer
99758        99759     Chirag Vaidya        Sales    Male   25   Developer
99948        99949  Sagarika Chitale           HR  Female   28    Engineer

        Hire_Date  Years_At_Company Education_Level  Performance_Score  \
93     2022-01-14                 3             PhD                  1
130    2009-11-07                15          Master                  1
156    2019-05-17                 5          Master                  1
195    2014-04-15                10          Master                  1
196    2018-11-25                 6     High School                  1
...           ...               ...             ...                ...
99430  2019-02-28                 6          Master                  1
99581  2021-03-02                 4        Bachelor                  1
99637  2023-02-26                 2        Bachelor                  1
99758  2020-06-22                 4        Bachelor                  1
99948  2023-07-27                 1          Master                  1

       Monthly_Salary  Work_Hours_Per_Week  Projects_Handled  \
93             236000                   49                 9
130            201000                   48                75
156            110000                   48                21
195            119000                   45                52
196             30000                   47                34
...               ...                  ...               ...
99430          127000                   44                25
99581          187000                   41                11
99637           73000                   41                14
99758           76000                   46                18
99948           84000                   43                 9

       Remote_Work_Frequency  Promotions  Employee_Satisfaction_Score  \
93                         0           1                         3.61
130                        0           5                         2.82
156                       50           0                         5.00
195                        0           1                         3.26
196                       20           1                         4.07
...                      ...         ...                          ...
99430                      0           1                         3.29
99581                     80           1                         4.71
99637                     20           0                         2.40
99758                     20           0                         2.08
99948                      0           0                         4.65

       Resigned
93        False
130       False
156       False
195       False
196       False
...         ...
99430     False
99581     False
99637     False
99758      True
99948     False

[1687 rows x 17 columns]
       Employee_ID                Name        Department  Gender  Age  \
0                1       Kishore Singh       Engineering    Male   39
3                4       Rakhi Pradhan                IT  Female   52
29              30     Sudhakar Prabhu  Customer Support    Male   55
48              49         Padma Dixit  Customer Support  Female   56
55              56        Rajani Nanda             Sales  Female   23
...            ...                 ...               ...     ...  ...
99917        99918       Vivek Pradhan        Operations    Male   48
99920        99921       Vignesh Panda        Operations    Male   59
99929        99930         Ritesh Bose                IT    Male   52
99933        99934  Shashank Panigrahi        Operations    Male   29
99943        99944         Mohan Verma  Customer Support    Male   22

         Job_Title   Hire_Date  Years_At_Company Education_Level  \
0      Sr. Manager  2018-11-09                 6        Bachelor
3          Manager  2014-04-14                10        Bachelor
29     Sr. Manager  2020-06-23                 4          Master
48     Sr. Manager  2001-07-22                23        Bachelor
55        Director  2023-08-25                 1        Bachelor
...            ...         ...               ...             ...
99917      Manager  2007-06-01                17        Bachelor
99920   Consultant  2010-03-02                15          Master
99929  Sr. Manager  2021-01-17                 4          Master
99933     Director  2023-07-24                 1             PhD
99943  Sr. Manager  2021-04-14                 3             PhD

       Performance_Score  Monthly_Salary  Work_Hours_Per_Week  \
0                      2          317000                   43
3                      3          330000                   42
29                     4          357000                   40
48                     3          738000                   41
55                     5          398000                   44
...                  ...             ...                  ...
99917                  3          409000                   49
99920                  2          343000                   45
99929                  4          366000                   42
99933                  3          549000                   40
99943                  4          338000                   41

       Projects_Handled  Remote_Work_Frequency  Promotions  \
0                     8                      0           1
3                    25                     20           4
29                    5                     50           1
48                   27                     50           5
55                    2                     50           0
...                 ...                    ...         ...
99917                29                      0           4
99920                48                     20           4
99929                 5                      0           1
99933                 2                      0           0
99943                 5                      0           0

       Employee_Satisfaction_Score  Resigned
0                             2.46      True
3                             1.98     False
29                            2.68     False
48                            2.98     False
55                            1.77      True
...                            ...       ...
99917                         3.83      True
99920                         3.80     False
99929                         2.34     False
99933                         3.30      True
99943                         2.35     False

[8370 rows x 17 columns]
       Employee_ID             Name        Department  Gender  Age  \
1788          1789       Ojas Patil             Sales    Male   40
2556          2557        Inder Pai           Finance    Male   25
3732          3733     Shanti Ghosh                IT  Female   37
4217          4218       Kajal Basu                IT  Female   22
5954          5955  Gitanjali Padhi        Operations  Female   34
...            ...              ...               ...     ...  ...
94331        94332   Sanjeev Thakur             Sales    Male   50
95461        95462     Prachi Menon       Engineering  Female   59
96776        96777     Lata Kashyap  Customer Support  Female   22
98402        98403     Reena Bhatia       Engineering  Female   18
99155        99156     Aditya Mehta        Operations    Male   51

         Job_Title   Hire_Date  Years_At_Company Education_Level  \
1788      Engineer  2019-04-23                 5        Bachelor
2556       Manager  2023-11-21                 1             PhD
3732    Technician  2020-01-04                 5     High School
4217   Sr. Manager  2023-10-16                 1          Master
5954     Developer  2021-10-08                 3        Bachelor
...            ...         ...               ...             ...
94331   Consultant  2022-04-01                 2          Master
95461      Manager  2017-08-13                 7        Bachelor
96776      Analyst  2023-07-20                 1        Bachelor
98402      Analyst  2024-04-05                 0        Bachelor
99155    Developer  2010-04-14                14          Master

       Performance_Score  Monthly_Salary  Work_Hours_Per_Week  \
1788                   4           88000                   60
2556                   2          228000                   58
3732                   3           28000                   58
4217                   3          248000                   58
5954                   3           70000                   58
...                  ...             ...                  ...
94331                  3          138000                   59
95461                  3          197000                   60
96776                  4           53000                   59
98402                  2           49000                   58
99155                  4          190000                   60

       Projects_Handled  Remote_Work_Frequency  Promotions  \
1788                 21                     80           1
2556                  4                     20           0
3732                 29                     20           1
4217                  2                      0           0
5954                 17                      0           0
...                 ...                    ...         ...
94331                11                     20           0
95461                18                      0           1
96776                 9                     50           0
98402                 5                     20           0
99155                56                     80           3

       Employee_Satisfaction_Score  Resigned
1788                          3.51      True
2556                          3.98     False
3732                          4.43     False
4217                          2.22     False
5954                          3.18      True
...                            ...       ...
94331                         2.35     False
95461                         3.32     False
96776                         4.84      True
98402                         3.52     False
99155                         4.57     False

[82 rows x 17 columns]
       Employee_ID               Name        Department  Gender  Age  \
2                3      Darsh Kaushik                IT    Male   58
30              31   Sagarika Chitale        Operations  Female   41
42              43    Sushil Hazarika  Customer Support    Male   55
115            116    Shashank Mallya        Operations    Male   49
130            131        Parul Yadav                IT  Female   51
...            ...                ...               ...     ...  ...
99910        99911      Santosh Reddy             Legal    Male   47
99911        99912         Raman Kaur                IT    Male   55
99930        99931       Dev Majumdar                IT    Male   42
99956        99957  Nishtha Deshpande  Customer Support  Female   52
99993        99994  Mridula Mukherjee         Marketing  Female   53

        Job_Title   Hire_Date  Years_At_Company Education_Level  \
2      Technician  2007-10-17                17     High School
30     Technician  2007-06-25                17        Bachelor
42      Developer  2008-05-16                16          Master
115     Developer  2006-12-04                18          Master
130       Analyst  2009-11-07                15          Master
...           ...         ...               ...             ...
99910    Engineer  2006-10-30                18        Bachelor
99911  Technician  2010-07-30                14     High School
99930  Technician  2013-02-09                12     High School
99956  Technician  2001-01-14                24     High School
99993  Technician  2011-01-30                14     High School

       Performance_Score  Monthly_Salary  Work_Hours_Per_Week  \
2                      3           54000                   50
30                     3           79000                   42
42                     3          232000                   47
115                    4          290000                   48
130                    1          201000                   48
...                  ...             ...                  ...
99910                  4          158000                   46
99911                  4           63000                   48
99930                  2           37000                   50
99956                  4           84000                   41
99993                  3           45000                   49

       Projects_Handled  Remote_Work_Frequency  Promotions  \
2                   101                      0           4
30                   98                     20           3
42                   80                     20           3
115                  75                     50           6
130                  75                      0           5
...                 ...                    ...         ...
99910                70                     20           3
99911                80                      0           6
99930                75                    100           2
99956               118                      0           6
99993                89                      0           2

       Employee_Satisfaction_Score  Resigned
2                             3.21     False
30                            4.62     False
42                            3.79      True
115                           4.42     False
130                           2.82     False
...                            ...       ...
99910                         2.89     False
99911                         4.57     False
99930                         4.61     False
99956                         3.83     False
99993                         3.05      True

[4186 rows x 17 columns]
       Employee_ID                 Name        Department  Gender  Age  \
21              22     Siddharth Sharma                IT    Male   56
94              95        Tushar Rajput  Customer Support    Male   46
115            116      Shashank Mallya        Operations    Male   49
142            143       Akash Rajkhowa                IT    Male   56
215            216           Kirti Naik        Operations  Female   55
...            ...                  ...               ...     ...  ...
99860        99861          Bharat Suri        Operations    Male   58
99863        99864      Trisha Rajkhowa       Engineering  Female   48
99893        99894  Gaurav Bhattacharya       Engineering    Male   51
99911        99912           Raman Kaur                IT    Male   55
99956        99957    Nishtha Deshpande  Customer Support  Female   52

        Job_Title   Hire_Date  Years_At_Company Education_Level  \
21      Developer  2009-08-07                15        Bachelor
94        Analyst  2010-10-28                14        Bachelor
115     Developer  2006-12-04                18          Master
142       Manager  1997-10-03                27        Bachelor
215      Engineer  1999-09-23                25        Bachelor
...           ...         ...               ...             ...
99860  Technician  2010-06-22                14     High School
99863    Engineer  2005-05-11                19          Master
99893  Technician  2006-08-06                18     High School
99911  Technician  2010-07-30                14     High School

In [31]:
employee_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 17 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Employee_ID                  100000 non-null  int64
 1   Name                         100000 non-null  object
 2   Department                   100000 non-null  object
 3   Gender                       100000 non-null  object
 4   Age                          100000 non-null  int64
 5   Job_Title                    100000 non-null  object
 6   Hire_Date                    100000 non-null  object
 7   Years_At_Company             100000 non-null  int64
 8   Education_Level              100000 non-null  object
 9   Performance_Score            100000 non-null  int64
 10  Monthly_Salary               100000 non-null  int64
 11  Work_Hours_Per_Week          100000 non-null  int64
 12  Projects_Handled             100000 non-null  int64
 13  Remote_Work_Frequency        100000 non-null  int64
 14  Promotions                   100000 non-null  int64
 15  Employee_Satisfaction_Score  100000 non-null  float64
 16  Resigned                     100000 non-null  bool
dtypes: bool(1), float64(1), int64(9), object(6)
memory usage: 12.3+ MB

In [32]:
from sqlalchemy import create_engine

In [42]:
dim_employee = employee_df[['Employee_ID','Name','Department','Gender','Age','Job_Title','Education_Level']]
fact_workload = employee_df[['Employee_ID','Work_Hours_Per_Week','Projects_Handled','Remote_Work_Frequency','Employee_Satisfaction_Score']]
fact_record = employee_df[['Employee_ID','Hire_Date','Years_At_Company','Performance_Score','Monthly_Salary','Promotions','Resigned']]
dim_employee.drop(columns=['index'], errors='ignore')
fact_workload.drop(columns=['index'], errors='ignore')
fact_record.drop(columns=['index'], errors='ignore')

,Employee_ID,Hire_Date,Years_At_Company,Performance_Score,Monthly_Salary,Promotions,Resigned
0,1,2018-11-09,6,2,317000,1,True
1,2,2019-04-09,5,3,103000,1,False
2,3,2007-10-17,17,3,54000,4,False
3,4,2014-04-14,10,3,330000,4,False
4,5,2023-06-27,1,3,62000,0,False
...,...,...,...,...,...,...,...
99995,99996,2021-06-24,3,4,96000,0,False
99996,99997,2024-09-11,0,3,68000,0,False
99997,99998,2019-02-26,6,3,91000,2,False
99998,99999,2017-07-19,7,3,212000,1,False
99999,100000,2017-11-20,7,4,104000,2,False

In [47]:
dim_employee.to_excel('dim_employee.xlsx', index=False)
fact_workload.to_excel('fact_workload.xlsx', index=False)
fact_record.to_excel('fact_record.xlsx', index=False)